/**
 * Every picture an offer can be drawn with: the entries of the game's `Offers`
 * addressable group, by the name a payload gives them.
 *
 * GENERATED by `npm run sync:offer-art` from OffStarsStudios/CliffHeroes@master. Do not edit by hand.
 * An offer naming a picture that is not here draws nothing in its place.
 */

import type { OfferArt } from './offerArt';

export const OFFER_ART_SOURCE = { repo: "OffStarsStudios/CliffHeroes", ref: "master", group: "Assets/AddressableAssetsData/AssetGroups/Offers.asset" };

export const OFFER_ART: readonly OfferArt[] = [
  { name: "FlickGhostOfferBG", address: "OfferImages/FlickGhostOfferBG", file: "Assets/Art/Menu/Offers/Flick-Ghost/FlickGhostOfferBG.jpg", slot: "background" },
  { name: "FlickGhostOfferButton", address: "OfferImages/FlickGhostOfferButton", file: "Assets/Art/Menu/Offers/Flick-Ghost/FlickGhostOfferButton.png", slot: "button" },
  { name: "FlickGhostOfferTop", address: "OfferImages/FlickGhostOfferTop", file: "Assets/Art/Menu/Offers/Flick-Ghost/FlickGhostOfferTop.jpg", slot: "topBar" },
  { name: "GuySuperSpaceBG", address: "OfferImages/GuySuperSpaceBG", file: "Assets/Art/Menu/Offers/Guy-SuperSpace/GuySpace - BG.png", slot: "background" },
  { name: "GuySuperSpaceButton", address: "OfferImages/GuySuperSpaceButton", file: "Assets/Art/Menu/Offers/Guy-SuperSpace/GuySpace - Button.png", slot: "button" },
  { name: "GuySuperSpaceTop", address: "OfferImages/GuySuperSpaceTop", file: "Assets/Art/Menu/Offers/Guy-SuperSpace/GuySpace - Header.png", slot: "topBar" },
];
