/**
 * Every reward the game can hand over, as the ID it answers to and the name a
 * sheet calls it by.
 *
 * GENERATED by `npm run sync:rewards` from the game's own assets. Do not edit
 * by hand: rewards are not authored anywhere in the game either, they are
 * derived at runtime from the heroes, skins, arenas, currencies and lootboxes
 * that exist, so the only list that can be trusted is one derived the same way.
 *
 * This is the vocabulary every config shares. A sheet's Rewards tab is a copy of
 * it, the reward library page renders it, and every exporter checks the IDs it
 * resolves against it - which is what turns "that reward does not exist" from
 * something the client logs at runtime into something the console refuses.
 */

/** What a reward hands over. Only currencies are named without their family. */
export type RewardFamily = 'currency' | 'hero' | 'skin' | 'arena' | 'lootbox';

export interface Reward {
  /** What the game answers to. Never built from the name. */
  id: string;
  /** What a sheet calls it: `<Family> - <Thing>`, or just the currency. */
  name: string;
  family: RewardFamily;
}

export const REWARDS: readonly Reward[] = [
  { id: 'reward.currency.coins', name: 'Coins', family: 'currency' },
  { id: 'reward.currency.cards', name: 'Upgrade Cards', family: 'currency' },
  { id: 'reward.currency.trophies', name: 'Trophies', family: 'currency' },
  { id: 'reward.currency.gems', name: 'Gems', family: 'currency' },
  { id: 'reward.currency.passTokens', name: 'Pass Tokens', family: 'currency' },
  { id: 'reward.hero.cliff', name: 'Hero - Cliff', family: 'hero' },
  { id: 'reward.hero.flick', name: 'Hero - Flick', family: 'hero' },
  { id: 'reward.hero.guy', name: 'Hero - Guy', family: 'hero' },
  { id: 'reward.hero.pedro', name: 'Hero - Pedro', family: 'hero' },
  { id: 'reward.hero.tank', name: 'Hero - Tank', family: 'hero' },
  { id: 'reward.hero.glint', name: 'Hero - Glint', family: 'hero' },
  { id: 'reward.hero.cinder', name: 'Hero - Cinder', family: 'hero' },
  { id: 'reward.skin.tank.flower', name: 'Skin - Tank Flower', family: 'skin' },
  { id: 'reward.skin.cliff.halloween', name: 'Skin - Cliff Halloween', family: 'skin' },
  { id: 'reward.skin.guy.pirate', name: 'Skin - Guy Pirate', family: 'skin' },
  { id: 'reward.skin.guy.space', name: 'Skin - Guy Space', family: 'skin' },
  { id: 'reward.skin.guy.superspace', name: 'Skin - Guy Super Space', family: 'skin' },
  { id: 'reward.skin.flick.ghost', name: 'Skin - Flick Ghost', family: 'skin' },
  { id: 'reward.skin.tank.space', name: 'Skin - Tank Space', family: 'skin' },
  { id: 'reward.skin.tank.nature', name: 'Skin - Tank Nature', family: 'skin' },
  { id: 'reward.skin.tank.pirate', name: 'Skin - Tank Pirate', family: 'skin' },
  { id: 'reward.skin.glint.space', name: 'Skin - Glint Space', family: 'skin' },
  { id: 'reward.skin.glint.nature', name: 'Skin - Glint Nature', family: 'skin' },
  { id: 'reward.skin.glint.rainbow', name: 'Skin - Glint Rainbow', family: 'skin' },
  { id: 'reward.skin.pedro.space', name: 'Skin - Pedro Space', family: 'skin' },
  { id: 'reward.skin.pedro.nature', name: 'Skin - Pedro Nature', family: 'skin' },
  { id: 'reward.skin.pedro.pirate', name: 'Skin - Pedro Pirate', family: 'skin' },
  { id: 'reward.skin.pedro.rainbow', name: 'Skin - Pedro Rainbow', family: 'skin' },
  { id: 'reward.skin.cinder.space', name: 'Skin - Cinder Space', family: 'skin' },
  { id: 'reward.skin.cinder.nature', name: 'Skin - Cinder Nature', family: 'skin' },
  { id: 'reward.skin.cinder.pirate', name: 'Skin - Cinder Pirate', family: 'skin' },
  { id: 'reward.skin.cinder.rainbow', name: 'Skin - Cinder Rainbow', family: 'skin' },
  { id: 'reward.skin.cliff.space', name: 'Skin - Cliff Space', family: 'skin' },
  { id: 'reward.skin.cliff.nature', name: 'Skin - Cliff Nature', family: 'skin' },
  { id: 'reward.skin.cliff.pirate', name: 'Skin - Cliff Pirate', family: 'skin' },
  { id: 'reward.skin.cliff.rainbow', name: 'Skin - Cliff Rainbow', family: 'skin' },
  { id: 'reward.skin.flick.space', name: 'Skin - Flick Space', family: 'skin' },
  { id: 'reward.skin.flick.nature', name: 'Skin - Flick Nature', family: 'skin' },
  { id: 'reward.skin.flick.pirate', name: 'Skin - Flick Pirate', family: 'skin' },
  { id: 'reward.skin.flick.rainbow', name: 'Skin - Flick Rainbow', family: 'skin' },
  { id: 'reward.arena.lostoasis', name: 'Arena - Lost Oasis', family: 'arena' },
  { id: 'reward.arena.mysticforest', name: 'Arena - Mystic Forest', family: 'arena' },
  { id: 'reward.arena.sakuracliffs', name: 'Arena - Sakura Cliffs', family: 'arena' },
  { id: 'reward.lootbox.common', name: 'Lootbox - Common', family: 'lootbox' },
  { id: 'reward.lootbox.rare', name: 'Lootbox - Rare', family: 'lootbox' },
  { id: 'reward.lootbox.legendary', name: 'Lootbox - Legendary', family: 'lootbox' },
];

/** Reward ID -> its entry. */
export const REWARDS_BY_ID = new Map(REWARDS.map((reward) => [reward.id, reward]));

/** Sheet name -> its entry, matched the way the lookup tabs match. */
export const REWARDS_BY_NAME = new Map(REWARDS.map((reward) => [reward.name.toLowerCase(), reward]));

/** Whether the game registers a reward under this ID. */
export function isRewardId(id: string): boolean {
  return REWARDS_BY_ID.has(id);
}
